# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/yakkety64"

  config.vm.hostname = "docker-host"
  #config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    #   # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end
  
  #config.vm.provision "shell", path: "../scripts/docker.sh"

  #config.vm.provision "file", source: "../../index.html", destination: "/var/www/index.html"
end
