
source "virtualbox-ovf" "autogenerated_1" {
  communicator         = "winrm"
  guest_additions_mode = "disable"
  headless             = true
  output_directory     = "./output/win${var.winversion}-updates/"
  shutdown_command     = "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\""
  shutdown_timeout     = "1h"
  source_path          = "./output/win${var.winversion}-base/win${var.winversion}-base.ovf"
  vboxmanage           = [["modifyvm", "{{ .Name }}", "--memory", "2048"], ["modifyvm", "{{ .Name }}", "--vram", "128"], ["modifyvm", "{{ .Name }}", "--cpus", "1"]]
  vm_name              = "win${var.winversion}-updates"
  winrm_password       = "${var.pwd}"
  winrm_timeout        = "12h"
  winrm_username       = "${var.user}"
}

build {
  sources = ["source.virtualbox-ovf.autogenerated_1"]

  provisioner "powershell" {
    elevated_password = "${var.pwd}"
    elevated_user     = "${var.user}"
    script            = "./packerfiles/scripts/windows-updates.ps1"
  }

  provisioner "windows-restart" {
    restart_timeout = "1h"
  }

  provisioner "powershell" {
    elevated_password = "${var.pwd}"
    elevated_user     = "${var.user}"
    inline            = ["Get-WUInstall -MicrosoftUpdate -AcceptAll -IgnoreReboot"]
  }

  provisioner "windows-restart" {
    restart_timeout = "1h"
  }

  provisioner "powershell" {
    elevated_password = "${var.pwd}"
    elevated_user     = "${var.user}"
    inline            = ["Get-WUInstall -MicrosoftUpdate -AcceptAll -IgnoreReboot"]
  }

  provisioner "windows-restart" {
    restart_timeout = "1h"
  }

}
